<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<body>

    <p>To Know More About!</p>


    <a href="javascript:;" class="bt-action " data="More Info">Magnasonic</a>
    <div class="bt-action-file" style="display: none;">
        <section class="progress-bar-wrapper">
            <div id="myProgress" class="progress-bar-cointainer" style="display:none;">
                <div id="myBar" class="animationStripes progress-bar">
                    <span class="progressbar-width" value=""></span>
                </div>
            </div>
        </section>
        <div class="add-image" style="display:none;">
        </div>
        <div class="add-button" style="display:none;">
            <button class="btn temp" style="display:none;" id="linkid" value="-">
                hello
            </button>
        </div>
        <div class="magnasonic">
            <h3 class="title">
                <img class="down-arrow" src='<?= $this->getViewFileUrl('Tychons_Popup::images/d.png'); ?>'>Click to find
                the best product for your need
            </h3>
            <div class="magnasonic-content">

                <div class="sound-base common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/Sound Base.jpeg'); ?>'>
                    <button class="sound-bases btn" value="Sound Base">Sound Base</button>
                </div>
                <div class="projector common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/projector.jpg'); ?>'>
                    <button class="projector btn" value="Projector">Projector</button>
                </div>
                <div class="jewelry-cleaner common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/jwellery-cleaner.jpg'); ?>'>
                    <button class="btn" value="Jewelry Cleaner">Jewelry Cleaner</button>
                </div>
                <div class="flim-scanner common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/Film-Scaner.jpg'); ?>'>
                    <button class="btn" value="Flim Scanner">Flim Scanner</button>
                </div>
                <div class="clock-radio common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/clock.jpg'); ?>'>
                    <button class="btn clock-radio" value="Clock-Radio">Clock/Radio</button>
                </div>
            </div>

           
 

        <!-- <iframe src="blank" id="iframe" scrolling="no" height="700px" width="100%" style="display:none;">
        </iframe> -->
        
        <div class="pdp" style="display:none;">
            <?php 
                    use Magento\Framework\App\Action\Action; 
                    $_productCollection = $block->getProductCollection();
                ?>
            <?php 
                if (is_array($_productCollection) || is_object($_productCollection))
                {
                    ?>
                    <?php 
                        foreach ($_productCollection as $_product): 
                    ?>
                    <?php 
                        echo "sku from collection=".$_product->getSku()."<br>";
                        $a="<span class='sku'></span>" ; 
                        echo "sku=".$a."<br>";
                        
                        if ($_product->getSku() == $a){
                    ?>
                    <?php 
                        $postParams = $block->getAddToCartPostParams($_product); 
                    ?>
                    <p class="done">YOU JUST FOUND WHAT YOU WERE LOOKING FOR!</p>
                    <span class="img yes-projection-clock">
                        <img class="prod-image" src=' <?php echo $_product->getImage();?>'>
                    </span>
                    <div class="prod-description">
                        <h3 class="product-name"> <?php echo $_product->getName();?></h3>
                        <div class="stocks-sku">
                            <span class="stock">
                                IN STOCK
                            </span> |
                            <span class="sku">
                                <?php echo $_product->getSku();?>
                            </span>
                        </div>
                        <h6 class="product-review">Be the first to review this product</h6>
                        <h4 class="price"> <?php echo $_product->getPrice()?></h4>
                        <p class="quantity">Quantity:</p>
                        <span>
                            <input style="width:40px ; height:40px" class="qty" type="number" value="1" min="1" max="5">
                        </span>
                        <div class="addtocart">
                            <button class="discover" type="button">Discover</button>
                            <?php
                                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
                                    if ($customerSession->isLoggedIn()) {
                                        $customerSession->getCustomerId();  // get Customer Id
                                        $customerSession->getCustomerGroupId();
                                        $customerSession->getCustomer();
                                        $customerSession->getCustomerData();
                                ?>
                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>"
                                method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
                                <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                    class="action tocart primary">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            </form>
                            <?php } else{?>
                            <a href="customer/account/login/">Please Login</a><?php  }?>
                            <?php  }
                   
                    
                endforeach;}?>
                </div>
            </div>
        </div>
    </div>
</body>

<script type="text/x-magento-init">
    {
 "*": {
 "Tychons_AddToCart/js/myjs" : {}
 }
 }
</script>