<?php 
use Magento\Framework\App\Action\Action; 
$_productCollection = $block->getProductCollection();
?>
<?php foreach ($_productCollection as $_product): ?>
    <?php if ($_product->getName() == "Alarm Clock Digital FM Radio" ): ?>
    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
    <?php echo $_product->getName()?>
    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
        
        <?php echo $block->getBlockHtml('formkey')?>
        <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                    class="action tocart primary">
                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
            </button>
    </form>
<?php endif; 
endforeach;?>