<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<body>

    <p>To Know More About!</p>


    <a href="javascript:;" class="bt-action " data="More Info">Magnasonic</a>
    <div class="bt-action-file" style="display: none;">
        <section class="progress-bar-wrapper">
            <div id="myProgress" class="progress-bar-cointainer" style="display:none;">
                <div id="myBar" class="animationStripes progress-bar">
                    <span class="progressbar-width" value=""></span>
                </div>
            </div>
        </section>
        <div class="add-image" style="display:none;">
        </div>
        <div class="add-button" style="display:none;">
            <button class="btn temp" style="display:none;" id="linkid" value="-">
                hello
            </button>
        </div>
        <div class="magnasonic">
            <h3 class="title">
                <img class="down-arrow" src='<?= $this->getViewFileUrl('Tychons_Popup::images/d.png'); ?>'>Click to find
                the best product for your need
            </h3>
            <div class="magnasonic-content">

                <div class="sound-base common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/Sound Base.jpeg'); ?>'>
                    <button class="sound-bases btn" value="Sound Base">Sound Base</button>
                </div>
                <div class="projector common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/projector.jpg'); ?>'>
                    <button class="projector btn" value="Projector">Projector</button>
                </div>
                <div class="jewelry-cleaner common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/jwellery-cleaner.jpg'); ?>'>
                    <button class="btn" value="Jewelry Cleaner">Jewelry Cleaner</button>
                </div>
                <div class="flim-scanner common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/Film-Scaner.jpg'); ?>'>
                    <button class="btn" value="Flim Scanner">Flim Scanner</button>
                </div>
                <div class="clock-radio common">
                    <img class="prod-image" style="margin:10px 0"
                        src='<?= $this->getViewFileUrl('Tychons_Popup::images/clock.jpg'); ?>'>
                    <button class="btn clock-radio" value="Clock-Radio">Clock/Radio</button>
                </div>
            </div>




            <!-- <iframe src="blank" id="iframe" scrolling="no" height="700px" width="100%" style="display:none;">
        </iframe> -->

            <div class="pdp" style="display:none;">
                from array <span class="sku"></span> /
           
            </div>

                <script >
                     var ret = array_list[outer][inner].replace('SKU:','');
                     //var prod_sku = $('.sku').text(ret);
               </script>
                    <div id="popup-ko-example" data-bind="scope:'popup-ko-example'"> 
                        <!-- ko template: getTemplate() --><!-- /ko -->
                        <script type="text/x-magento-init">
                            {
                                "*": {
                                   "Magento_Ui/js/core/app": {
                                        "components": {
                                            "popup-ko-example": {
                                                "component": "Tychons_AddToCart/js/myjs"
                                            }
                                        }
                                    }
                                }
                            }
                        </script>
                    </div>
                   <!--  <div data-bind='text: popup'></div> -->
                <?php 
              /*  $zz= $block->getaddtocart('<span class="sku"></span>');
               echo $zz; */

              // $content="<span class='sku'></span>";
              // echo "hellooo". $new_string = preg_replace('/<span[^>]+\>/i', '!', $content); 

               //$qq= "<script>document.write(ret);</script>";
              // echo $qq;

               //$html = preg_replace('<script>document.write(ret);</script>#is', '',$html);
              // echo "html".$html;


              //$textBox1=$block->getaddtocart('<span class="sku"></span>');
              //$returnData = array('success' => FALSE, 'textBox1' => $textBox1);
              //echo json_encode($returnData);

               $pidd= $block->getaddtocarts();
             
              // echo $pidd;
              $sku="CR-63";
            //$skuu= "<script> $('.sku').text()</script>";
            //$sku=$_REQUEST["value"];
           // $sku ='<span class="sku"></span>';
           // $skuu=$sku;
           // echo $skuu; 
           $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
            $productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
           // $product = $productRepository->get("<div data-bind='text: textBox1'></div>");
            // $productid = $product->getId();
            $product=$productRepository->getById($pidd);
            $productid = $product->getId();
            //$product=$productRepository->getById($productid);
            //$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
            //$addToCartUrl = $cartHelper->getAddUrl($product);
            $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
            $addToCartUrl =  $listBlock->getAddToCartUrl($product);
            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $productid]);
        ?>
  
         
                                     
                <p class="done">YOU JUST FOUND WHAT YOU WERE LOOKING FOR!</p>
                <span class="img yes-projection-clock">
                    <img class="prod-image" src=' <?php echo $product->getImage();?>'>
                </span>
                <div class="prod-description">
                    <h3 class="product-name"> <?php echo $product->getName();?></h3>
                    <div class="stocks-sku">
                        <span class="stock">
                            IN STOCK
                        </span> |
                        <span class="sku">
                            <?php echo $product->getSku();?>
                        </span>
                    </div>
                    <h6 class="product-review">Be the first to review this product</h6>
                    <h4 class="price"> <?php echo $product->getPrice()?></h4>
                    <p class="quantity">Quantity:</p>
                    <span>
                        <input style="width:40px ; height:40px" class="qty" type="number" value="1" min="1" max="5">
                    </span>
                    <div class="addtocart">
                        <button class="discover" type="button">Discover</button>
                        <?php
                                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
                                    if ($customerSession->isLoggedIn()) {
                                        $customerSession->getCustomerId();  // get Customer Id
                                        $customerSession->getCustomerGroupId();
                                        $customerSession->getCustomer();
                                        $customerSession->getCustomerData();
                                       
                                        ?>
                        <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
                            <?php echo $block->getBlockHtml('formkey')?>
                            <div class="btn">
                                <button type="submit" title="Add to Cart" class="action tocart primary">
                                    <span>Add to Cart</span>
                                </button>
                            </div>
                        </form><?php
                        } else{?>
                        <a href="customer/account/login/">Please Login</a>
                        <?php 
                         }?>

                    </div>
                </div>
            </div>
        </div>
</body>

<script type="text/x-magento-init">
    {
 "*": {
 "Tychons_AddToCart/js/myjs" : {}
 }
 }
</script>