
<img src='<?= $this->getViewFileUrl('Tychons_CustomTab::images/delivery_info.png'); ?>' alt="image-icon">

<!-- <script type="text/x-magento-init">
    {
        "*": {
            "popupJs": {}
        }
    }
</script>

<style type="text/css">
		.modal-popup .modal-inner-wrap {
			width: 100%;
			margin-top: 0px;
			margin-bottom: 0px;
			height: 100%;
		}
		.modal-content {
			width: 100%;
			max-width: 1240px;
			margin: 0 auto;
		}
		.addtocart {
			margin-top: 10px;
		}
		.discover{
			margin-right:10px;
		}
		.bt-action {
			/* border: 1px solid black; */
			background-color: pink;
			background-image: linear-gradient(to right,#FF6480, #F22E63);
            padding:
			/* padding: 6px; */
			/* margin-right:10px; */
            /* margin-bottom:10px; */
		}
		.magnasonic{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
		.sound-base{
			display:block;
			align-items:center;
		}
		
		
		
		span.yes-projection-clock {
			display: flow-root;
			
			max-width: 225px;
			margin: auto;}
			.done{
			display: flex;
			margin: auto;
			max-width: 330px;
			padding-bottom: 25px;
		}
		.addtocart {
			margin-top: 10px;
			display: flex;
			align-items: center;
			justify-content: space-around;
			max-width: 300px;
			margin: auto;
		}
		.btnsubmmit{
			color: white !important;
			background-image: linear-gradient(to right,#FF6480, #F22E63);
			padding: 6px;
			margin-right:10px;
		}
		.advanced-subdiv{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}	
		
		.projection-aux-no-usb-charging{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
		.yes-usb-charging{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
		.yes-usb-charging-ab{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
		.bluetooth{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
		.bluetooth-ab{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
		.bluetooth-ab-no{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
		.display-color-am{
			display:flex;
			align-items:center;
			justify-content:space-around;
			height: 400px;
		}
	
	</style>
 -->

